### ISSUE TITLE
二日目タスク

### ISSUE THREAD

**Issue by Altech** [wantedly/reception-swift#6]
## iOS

- [x] キャンセルを押してメンバー一覧に遷移
- [x] Select -> Call への遷移を NavigationController への push に変更（戻れるようにするため）
- [x] 完了画面からタイトル画面に（一定時間で？）戻る
- [x] 検索を non-case-sensitive にする
- [ ] メンバーのリストを使用頻度順に並べる
- [ ] 回転させない

### バグ
- [x] アイコン画像を丸く切り取れていない（SDWebImage との兼ね合い？）

### デザイン周り
- [x] スプラッシュ画面と最初のビューコントローラでロゴの位置がずれる
- [x] 検索ボックスの下部に線を入れる
- [x] テーブルビューの上部スクロール余白？の設定
- [x] テーブルビューのアイコン画像の位置をセルの上部に合わせる
- [x] テーブルビューのセルの区切り線の開始位置をアイコンの右側からに変更する
- [x] アイコン画像をクリックするとアニメーションで遷移する
- [ ] 完了画面にフェードアウト＆フェードインで遷移する
- [ ] アイコン画像をロードしてないときの画像用意
- [ ] Main.storyboard を AutoLayout して warning 除去

## サーバーとの連携

- [x] メンバーのリストを REST で取ってきて設定
- [x] エンドポイントを定数に入れる
- [ ] 取ってきたリストをキャッシュする

## その他

- 1x, 3x 画像用意

**Comment by south37** [comment]
### iOS 追加
- 呼び出しを開始(Select -> Call)して30秒間レスポンスがなければ、CSへの呼び出しのリクエストを送る(POST /visitors/cs)

**Comment by Altech** [comment]
とりあえず通して動いたので今日はこれまで！ :tada: 
次 #28

**Comment by Altech** [comment]
とりあえず通して動いたので今日はこれまで！ :tada: 
次 #28
